### ISSUE TITLE
Failed require 'ruby_odata' in Ruby 2.7.0

### ISSUE THREAD

**Issue by demetrius2003** [visoft/ruby_odata#79]
Install gem steps seems to be ok. But then:
Traceback (most recent call last):
        2: from C:/Ruby27-x64/bin/test.rb:1:in `<main>'
        1: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb
:92:in `require'
C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
: cannot load such file -- ruby_odata (LoadError)
        16: from C:/Ruby27-x64/bin/test.rb:1:in `<main>'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:156:in `require'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:168:in `rescue in require'
        13: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:168:in `require'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ruby_odata-0.1.6/lib/rub
y_odata.rb:8:in `<top (required)>'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:72:in `require'
        10: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:72:in `require'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib
/active_support/core_ext.rb:1:in `<top (required)>'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib
/active_support/core_ext.rb:1:in `each'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib
/active_support/core_ext.rb:2:in `block in <top (required)>'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:92:in `require'
         5: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:92:in `require'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib
/active_support/core_ext/object.rb:3:in `<top (required)>'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:72:in `require'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.r
b:72:in `require'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib
/active_support/core_ext/object/duplicable.rb:80:in `<top (required)>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-4.1.16/lib/active_support/c
ore_ext/object/duplicable.rb:82:in `<class:BigDecimal>': undefined method `new'
for BigDecimal:Class (NoMethodError)

**Comment by visoft** [comment]
I suspect this is because of Ruby 2.7. I'll try to look into it, but would appreciate a PR if you have time.

**Comment by visoft** [comment]
Also, try the develop branch to see if that works.
